---
- hosts: localhost
  become: yes
  vars_files:
  - vars/main.yaml
  - vars/version.yaml
  roles:
  - golang
  - nodejs
  - ruby
  tasks:
  - name: configure vimrc
    include_role:
      name: custom/vim

  - name: configure bashrc
    when: item['enable']
    blockinfile:
      dest: "{{ item['home'] }}/.bashrc"
      block: "{{ bashrc_config }}"
      backup: yes
      marker: "# {mark} bashrc_config managed by rayshoo/plang"
    with_items: "{{ targets }}"
    register: result

  - name: Alert
    when: result['changed']
    debug:
      msg: If your ansible hosts include localhost, type 'source ~/.bashrc' in your shell
