---
- hosts: localhost
  become: yes
  vars:
    local:
      user: "{{ lookup('env','USER') }}"
      home: "{{ lookup('env','HOME') }}"
    targets:
    - { enable: yes, home: "{{ local['home'] }}" }
    - { enable: yes, home: /root }
    version:
      golang: 1.16.7
      nodejs: 14.17.5
      ruby: 3.0.2
      rbenv: 1.1.2
      ruby_build: 20210804
      git: latest
  roles:
  - golang
  - nodejs
  tasks:
  - name: configure bashrc
    when: item['enable']
    blockinfile:
      dest: "{{ item['home'] }}/.bashrc"
      block: "{{ bashrc_config }}"
      backup: yes
      marker: "# {mark} bashrc_config managed by rayshoo/env"
    with_items: "{{ targets }}"
    register: result

  - name: Alert
    when: result['changed']
    debug:
      msg: If your ansible hosts include localhost, type 'source ~/.bashrc' in your shell
